name = "hadwiger-challenge"
version = "0.1.0"
keywords = ["math"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "Matroid"
git = "https://github.com/utkuokur/Matroid.git"
rev = "a17ac77fcd5080935198c2520755372fd33ac4c3"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "Defs_and_Lems"

[[lean_lib]]
name = "Challenges"

